// <auto-generated />
using System;
using Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(EasyHotelDbContext))]
    partial class EasyHotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Core.Domain.Bed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Beds");
                });

            modelBuilder.Entity("Data.Core.Domain.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CheckIn");

                    b.Property<DateTime?>("CheckOut");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("FlCheckOut")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("GuestNumber");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("RoomId");

                    b.Property<decimal>("RoomRate");

                    b.Property<decimal?>("TotalBill");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Data.Core.Domain.DayRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId");

                    b.Property<DateTime>("DayRoomDate");

                    b.Property<decimal>("DayRoomPrice");

                    b.Property<int>("GuestsQty");

                    b.Property<bool>("PaymentFlag");

                    b.Property<int>("RoomId");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("RoomId");

                    b.ToTable("DayRoom");
                });

            modelBuilder.Entity("Data.Core.Domain.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<DateTime>("Created");

                    b.Property<string>("DsComplemento");

                    b.Property<DateTime?>("DtNascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(30);

                    b.Property<string>("Fone")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<int>("Numero");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Data.Core.Domain.GuestBook", b =>
                {
                    b.Property<int>("BookId");

                    b.Property<int>("GuestId");

                    b.HasKey("BookId", "GuestId");

                    b.HasIndex("GuestId");

                    b.ToTable("GuestBooks");
                });

            modelBuilder.Entity("Data.Core.Domain.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CurrentBookId");

                    b.Property<int>("DoorNumber");

                    b.Property<int>("FloorNumber");

                    b.Property<string>("RoomDescription")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<int>("RoomStateId");

                    b.Property<int>("RoomTypeId");

                    b.HasKey("Id");

                    b.HasIndex("CurrentBookId")
                        .IsUnique()
                        .HasFilter("[CurrentBookId] IS NOT NULL");

                    b.HasIndex("RoomStateId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Data.Core.Domain.RoomBed", b =>
                {
                    b.Property<int>("RoomId");

                    b.Property<int>("BedId");

                    b.Property<int>("NumberBeds");

                    b.HasKey("RoomId", "BedId");

                    b.HasIndex("BedId");

                    b.ToTable("RoomBeds");
                });

            modelBuilder.Entity("Data.Core.Domain.RoomState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("RoomStates");
                });

            modelBuilder.Entity("Data.Core.Domain.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");
                });

            modelBuilder.Entity("Data.Core.Domain.Book", b =>
                {
                    b.HasOne("Data.Core.Domain.Room", "Room")
                        .WithMany("Books")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Data.Core.Domain.DayRoom", b =>
                {
                    b.HasOne("Data.Core.Domain.Book", "Book")
                        .WithMany("DayRooms")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Data.Core.Domain.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Data.Core.Domain.GuestBook", b =>
                {
                    b.HasOne("Data.Core.Domain.Book", "Book")
                        .WithMany("Guests")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Data.Core.Domain.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Data.Core.Domain.Room", b =>
                {
                    b.HasOne("Data.Core.Domain.Book", "CurrentBook")
                        .WithOne("CurrentRoom")
                        .HasForeignKey("Data.Core.Domain.Room", "CurrentBookId");

                    b.HasOne("Data.Core.Domain.RoomState", "RoomState")
                        .WithMany()
                        .HasForeignKey("RoomStateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Data.Core.Domain.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Data.Core.Domain.RoomBed", b =>
                {
                    b.HasOne("Data.Core.Domain.Bed", "Bed")
                        .WithMany()
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Data.Core.Domain.Room", "Room")
                        .WithMany("Beds")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
